openapi: 3.0.3

info:
  version: 0.0.1
  title: Contact center service
  description: |
servers:
  - url: http://localhost:9000/

paths:

  /api/questions/modify_answer_user_tasks/{user_task_id}:
    parameters:        
      - $ref: "lib/parameters/user_task_id_parameter.yaml"
    get:
      tags:
        - modify answer user tasks
      summary: Gets a modify answer task.
      operationId: GetModifyAnswerTask
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "lib/responses/modify_answer_user_task_response.yaml"
        404:
          $ref: "lib/responses/types/404.yaml"

  /api/questions/modify_answer_user_tasks/{user_task_id}/modify:
    parameters:        
      - $ref: "lib/parameters/user_task_id_parameter.yaml"
    put:
      tags:
        - modify answer user tasks
      summary: Completes the modify answer task by modifing the answer.
      operationId: ModifyAnswer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "lib/commands/modify_answer_command.yaml"
      responses:
        202:
          description: Accepted
        404:
          $ref: "lib/responses/types/404.yaml"