openapi: 3.0.3

info:
  version: 0.0.1
  title: Contact center service
  description: |
servers:
  - url: http://localhost:9000/

paths:

  /api/questions:
    post:
      tags:
        - questions
      summary: Starts the answer question process.
      description: |
        
      operationId: RegisterQuestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "commands/register_question_command.yaml"
      responses:
        201:
          $ref: "responses/types/201.yaml"
    get:
      tags:
        - questions
      summary: Gets a list of answer question processes.
      operationId: GetQuestions
      parameters:
        - $ref: "parameters/question_id_offset_parameter.yaml"
        - $ref: "parameters/limit_parameter.yaml"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "responses/questions_response.yaml"

  /api/questions/{question_id}:
    parameters:
      - $ref: "parameters/question_id_parameter.yaml"
    get:
      tags:
        - questions
      summary: Gets an answer question proces.
      operationId: GetQuestion
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "responses/question_response.yaml"
        404:
          $ref: "responses/types/404.yaml"
          
  /api/questions/{question_id}/end:
    parameters:
      - $ref: "parameters/question_id_parameter.yaml"
    put:
      tags:
        - questions
      summary: Ends the answer question process.
      operationId: EndQuestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "commands/end_question_command.yaml"
      responses:
        202:
          description: Accepted
  
  /api/questions/answer_question_tasks/{user_task_id}:
    parameters:        
      - $ref: "parameters/user_task_id_parameter.yaml"
    get:
      tags:
        - answer question tasks
      summary: Gets an answer question task.
      operationId: GetAnswerQuestionTask
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "responses/answer_question_task_response.yaml"
        404:
          $ref: "responses/types/404.yaml"

  /api/questions/answer_question_tasks/{user_task_id}/answer:
    parameters:        
      - $ref: "parameters/user_task_id_parameter.yaml"
    put:
      tags:
        - answer question tasks
      summary: Completes the answer question task by answering the question.
      operationId: AnswerQuestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "commands/answer_question_command.yaml"
      responses:
        202:
          description: Accepted
        404:
          $ref: "responses/types/404.yaml"
          
  /api/questions/review_answer_tasks/{user_task_id}:
    parameters:        
      - $ref: "parameters/user_task_id_parameter.yaml"
    get:
      tags:
        - review answer tasks
      summary: Gets a review answer task.
      operationId: GetReviewAnswerTask
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "responses/review_answer_task_response.yaml"
        404:
          $ref: "responses/types/404.yaml"

  /api/questions/review_answer_tasks/{user_task_id}/accept:
    parameters:        
      - $ref: "parameters/user_task_id_parameter.yaml"
    put:
      tags:
        - review answer tasks
      summary: Completes the review answer task by accepting the answer.
      operationId: AcceptAnswer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "commands/accept_answer_command.yaml"
      responses:
        202:
          description: Accepted
        404:
          $ref: "responses/types/404.yaml"

  /api/questions/review_answer_tasks/{user_task_id}/reject:
    parameters:        
      - $ref: "parameters/user_task_id_parameter.yaml"
    put:
      tags:
        - review answer tasks
      summary: Completes the review answer task by rejecting the answer.
      operationId: RejectAnswer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "commands/reject_answer_command.yaml"
      responses:
        202:
          description: Accepted
        404:
          $ref: "responses/types/404.yaml"
          
  /api/questions/modify_answer_tasks/{user_task_id}:
    parameters:        
      - $ref: "parameters/user_task_id_parameter.yaml"
    get:
      tags:
        - modify answer tasks
      summary: Gets a modify answer task.
      operationId: GetModifyAnswerTask
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "responses/modify_answer_task_response.yaml"
        404:
          $ref: "responses/types/404.yaml"

  /api/questions/modify_answer_tasks/{user_task_id}/modify:
    parameters:        
      - $ref: "parameters/user_task_id_parameter.yaml"
    put:
      tags:
        - modify answer tasks
      summary: Completes the modify answer task by modifing the answer.
      operationId: ModifyAnswer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "commands/modify_answer_command.yaml"
      responses:
        202:
          description: Accepted
        404:
          $ref: "responses/types/404.yaml"