openapi: 3.0.3

info:
  version: 0.0.1
  title: Contact center service
  description: |
servers:
  - url: http://localhost:9000/

paths:

  /api/questions:
    post:
      tags:
        - questions
      summary: Starts the answer question process.
      description: |
        
      operationId: RegisterQuestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "commands/register_question_command.yaml"
      responses:
        201:
          $ref: "responses/types/201.yaml"
    get:
      tags:
        - questions
      summary: Gets a list of answer question processes.
      operationId: GetQuestions
      parameters:
        - $ref: "parameters/question_id_offset_parameter.yaml"
        - $ref: "parameters/limit_parameter.yaml"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "responses/questions_response.yaml"

  /api/questions/{question_id}:
    parameters:
      - $ref: "parameters/question_id_parameter.yaml"
    get:
      tags:
        - questions
      summary: Gets an answer question proces.
      operationId: GetQuestion
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "responses/question_response.yaml"
        404:
          $ref: "responses/types/404.yaml"
          
  /api/questions/{question_id}/end:
    parameters:
      - $ref: "parameters/question_id_parameter.yaml"
    put:
      tags:
        - questions
      summary: Ends the answer question process.
      operationId: EndQuestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "commands/end_question_command.yaml"
      responses:
        202:
          description: Accepted