openapi: 3.0.3

info:
  version: 0.0.1
  title: Contact center service
  description: |
servers:
  - url: http://localhost:9000/

paths:
          
  /api/questions/review_answer_user_tasks/{user_task_id}:
    parameters:        
      - $ref: "data-dictionary/parameters/user_task_id_parameter.yaml"
    get:
      tags:
        - review answer user tasks
      summary: Gets a review answer task.
      operationId: GetReviewAnswerTask
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "data-dictionary/responses/review_answer_user_task_response.yaml"
        404:
          $ref: "data-dictionary/responses/types/404.yaml"

  /api/questions/review_answer_user_tasks/{user_task_id}/accept:
    parameters:        
      - $ref: "data-dictionary/parameters/user_task_id_parameter.yaml"
    put:
      tags:
        - review answer user tasks
      summary: Completes the review answer task by accepting the answer.
      operationId: AcceptAnswer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "data-dictionary/commands/accept_answer_command.yaml"
      responses:
        202:
          description: Accepted
        404:
          $ref: "data-dictionary/responses/types/404.yaml"

  /api/questions/review_answer_user_tasks/{user_task_id}/reject:
    parameters:        
      - $ref: "data-dictionary/parameters/user_task_id_parameter.yaml"
    put:
      tags:
        - review answer user tasks
      summary: Completes the review answer task by rejecting the answer.
      operationId: RejectAnswer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "data-dictionary/commands/reject_answer_command.yaml"
      responses:
        202:
          description: Accepted
        404:
          $ref: "data-dictionary/responses/types/404.yaml"