name: BUILD & DEPLOY

on: [push]

jobs:

  build:

    env:
      RESOURCE_GROUP: synion
      STORAGE_ACCOUNT: synionstorage
      STORAGE_CONTAINER: docs-synion-nl
      CDN_PROFILE: synion-cdn
      CDN_ENDPOINT: docs-synion-www
      STORAGE_BUCKET: blog

    runs-on: ubuntu-latest

    steps:

      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          path: main

      - uses: octokit/request-action@v2.x
        id: get-branches
        with:
          route: GET /repos/${{ github.repository }}/branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout md-docs repo
        uses: actions/checkout@v2
        with:
          repository: synionnl/living-documentation
          path: md-docs

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install md-docs
        working-directory: md-docs
        run: |
          npm install
          npm link

      - name: Build website
        id: build-website
        working-directory: main
        run: |
          md-docs
          BRANCHES=$(cat ./dist/branches.json)
          BRANCHES="${BRANCHES//'%'/'%25'}"
          BRANCHES="${BRANCHES//$'\n'/'%0A'}"
          BRANCHES="${BRANCHES//$'\r'/'%0D'}"
          echo "::set-output name=branches::$BRANCHES"

      - name: Build websites
        working-directory: main
        run: |
          git fetch
          for B in $(echo $BRANCHES | jq -r 'sort_by(.path) | .[].name')
          do
              git checkout "$B"
              md-docs
          done
        env:
          BRANCHES: ${{ steps.build-website.outputs.branches}}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name "$STORAGE_ACCOUNT" -d "$STORAGE_CONTAINER/$STORAGE_BUCKET" -s "./main/dist"      

      - name: Prune feature branches
        uses: synionnl/prune-features@main
        with:
          storage-account: ${{ env.STORAGE_ACCOUNT }}
          storage-container: ${{ env.STORAGE_CONTAINER }}
          bucket: ${{ env.STORAGE_BUCKET }}
          branches: ${{ steps.build-website.outputs.branches }}
      
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az cdn endpoint purge --content-paths  "/$STORAGE_BUCKET/*" --profile-name "$CDN_PROFILE" --name "$CDN_ENDPOINT" --resource-group "$RESOURCE_GROUP"

      - name: Azure logout
        if: always()
        run: |
          az logout
