name: md-docs

on:
  workflow_dispatch:
  push:

jobs:

  md-docs:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - uses: actions/checkout@v2

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install md-docs
        run: |
          npm i @biz-dev-ops/md-docs@latest

      - name: Install PrinceXml
        run: |
          sudo apt-get install libgif7
          sudo apt-get install libavif16
          node node_modules/@biz-dev-ops/md-docs/node_modules/prince/prince-npm.js install

      - name: Build
        run: |
          node ../bin/index.js -f

      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_CREDENTIALS }}
          repo_token: ${{ github.token }}
          action: upload
          app_location: /dist
          skip_app_build: true
